### ISSUE TITLE
What do you think about the idea to merge forget.sh at the end of backup.sh file?

### ISSUE THREAD

**Issue by stephane-klein** [Its-Alex/restic-ftp-docker#3]
Suggestion: what do you think of the idea of launching [`restic forget`](https://github.com/Its-Alex/restic-ftp-docker/blob/5e7152ee719dbfdda3545534e92e7bff47c45670/forget.sh#L14C9-L14C22) after [`restic backup`](https://github.com/Its-Alex/restic-ftp-docker/blob/5e7152ee719dbfdda3545534e92e7bff47c45670/backup.sh#L16) and removing [`forget.sh`](https://github.com/Its-Alex/restic-ftp-docker/blob/5e7152ee719dbfdda3545534e92e7bff47c45670/forget.sh#L1) file?

With an if on the `RESTIC_DOCKER_IS_FORGET_ENABLE` variable?

This could :

- simplify implementation;
- simplify use and understanding of the Docker image, saving users the hassle of having to configure the forget cron.

I'm thinking of implementing this in https://github.com/stephane-klein/restic-pg_dump-docker/tree/june-2024-working-session

**Comment by Its-Alex** [comment]
@stephane-klein Good idea, it's done
